### ISSUE TITLE
Question about the cross-domain video discriminator

### ISSUE THREAD

**Issue by SYL-322** [snap-research/MoCoGAN-HD#1]
Hi, thanks for your great work!

I have a question about the cross-domain video discriminator. 

According to your paper, you can learn to synthesize video content from one dataset A (such as Anime-Face) while motion part from another dataset B (such as VoxCeleb). In this mode, I think the video discriminator will first learn how to classify the anime and the real person's contents, rather than distinguish meaningful motions. How do you ensure that the video discriminator is helpful during training in this mode?

**Comment by bluer555** [comment]
Hi Mofafa,

We also noticed this problem. The discriminator can easily reject a synthesized video by content not motion. We tried to solve this problem with some motion-sensitive design (e.g. discriminator with optical flows as the input) but the results are not good. So our motion for cross-domain is not as good as the in-domain case, I think it's an interesting direction for future work.
