### ISSUE TITLE
How to train on a custom dataset?

### ISSUE THREAD

**Issue by skymanaditya1** [snap-research/MoCoGAN-HD#16]
I have a custom dataset of face videos from the How2Sign dataset. I have the dataset in the format required by this repository. What are the steps for training on a custom dataset?

**Comment by alanspike** [comment]
You could first train a StyleGAN image generator and then following the training steps in README such as the [FaceForensic](https://github.com/snap-research/MoCoGAN-HD#faceforensics).

**Comment by skymanaditya1** [comment]
Thank you for the reply! Closing

**Comment by SoftPointer** [comment]
Did you use the pretrained model from the official stylegan2 repo or this repo?
