### ISSUE TITLE
Incorrect link for the image generator checkpoint on FaceForensics

### ISSUE THREAD

**Issue by universome** [snap-research/MoCoGAN-HD#3]
Hi! Thank you for the project and the codebase! I noticed that for some datasets, links to the pretrained models do not work: e.g. the image generator link on FaceForensics leads to [https://github.com/snap-research/MoCoGAN-HD/blob/main/pretrained_models/faceforensics-fid10.9920-snapshot-008765.pt](https://github.com/snap-research/MoCoGAN-HD/blob/main/pretrained_models/faceforensics-fid10.9920-snapshot-008765.pt), which does not exist (same for (Anime, VoxCeleb) and (AFHQ, VoxCeleb) cross-domain image generators). Could you please provide a link for the pretrained image generator on FaceForensics?

**Comment by alanspike** [comment]
Hey, the links have been fixed.

**Comment by universome** [comment]
Thank you!
