### ISSUE TITLE
Usage of UCF-101 dataset

### ISSUE THREAD

**Issue by sihyun-yu** [snap-research/MoCoGAN-HD#4]
Hi, thank you for sharing the code of your elegant work!

I have a question about the experimental setup on experiments with UCF-101 dataset.
Did you use the "train" split from the UCF-101 dataset or the whole dataset without split?

Thank you in advance!

Sincerely,
Sihyun

**Comment by bluer555** [comment]
Hi, 

we use all 13,320 videos for training without the split.

Thanks!

**Comment by sihyun-yu** [comment]
Thank you for the clarification!

**Comment by sihyun-yu** [comment]
Hello! I have one more question.
You compared with baselines which mostly uses "train" split for the generator for the evaluation. However, you use all data for training; isn't it unfair comparison?

Sincerely,
Sihyun.

**Comment by bluer555** [comment]
Hi Sihyun,

We follow the settings of DVD-GAN, the strongest baseline prior to our work. 

The main drawback of the UCF-101 dataset is the relatively poor image generation quality (>40 FID), our video synthesis quality (FVD) is highly correlated to the image generation when the FID is not good enough. To be honest, we are not sure if using the training split can improve the FID or not. It is interesting to perform an experiment on this.

Thanks!
