### ISSUE TITLE
Hyperparameters to train StyleGANv2 on UCF-101

### ISSUE THREAD

**Issue by sihyun-yu** [snap-research/MoCoGAN-HD#5]
Hello! Thanks again for providing the implementation.
I am trying to retrain a "unconditional" image generator from scratch on the UCF-101 dataset using StyleGANv2 as you suggested.
Did you use specific hyperparameters to train such a model to reach the reported FID?
If so, can you share those hyperparameters?

Thanks in advance!

Sincerely,
Sihyun

**Comment by sihyun-yu** [comment]
Moreover, I evaluated FID given your pre-trained model on UCF-101, but the calculated FID seems much larger (140) than the reported (45). Am I missing something?

**Comment by alanspike** [comment]
Hi @sihyun-yu, have you tried to use the augmentation from [this work](https://github.com/mit-han-lab/data-efficient-gans)?

The FID was calculated during training from [StyleGAN2](https://github.com/NVlabs/stylegan2).

**Comment by sihyun-yu** [comment]
Hello! So you trained your model with such augmentations? I haven't tried leveraging augmentations for training such model, and I will try out. Thanks!

For FID, I mis-implemented something - sorry for the confusion.

Thank you in advance!
