### ISSUE TITLE
README should be updated

### ISSUE THREAD

**Issue by TiankaiHang** [snap-research/MoCoGAN-HD#6]
Some orders in README and current scripts don't match.
![image](https://user-images.githubusercontent.com/52823230/132695819-bb08c393-238c-448e-a11a-c49636e9005b.png)

should run like this
`sh script/ffhq-vox/run_evaluate_1024.sh` and `sh script/ffhq-vox/run_get_stats_pca_1024.sh`

**Comment by alanspike** [comment]
Thank you for noticing this. Just updated the commands.
