### ISSUE TITLE
Did you use any truncation or curation for the released samples?

### ISSUE THREAD

**Issue by universome** [snap-research/MoCoGAN-HD#8]
Hi! Could you please tell whether you used any truncation for the content or motion codes or curated the samples for these generations: https://github.com/snap-research/MoCoGAN-HD#faceforensics-1 ? I used your pretrained checkpoint, PCA stats and the pretrained G to generate samples with `--n_frames_G=32` and without spatial noise. And the results feel of lower quality compared to the ones which you show in your README.md. Here is the samples I got (sorry for the external link, github for some reason does not want to upload the gif even if it is less than 10mb):

https://i.imgur.com/1QRibnD.mp4

For example, the motion diversity is not that good, i.e. the heads do not "speak". Could you tell, why there is such a difference?

**Comment by alanspike** [comment]
We didn't use curation. I realize the checkpoint for faceforensics might from a previous version of the code. I'll check that later.

**Comment by hsi1032** [comment]
Hi,

@alanspike, do you have any plans to update the checkpoint for faceforensics dataset?

**Comment by alanspike** [comment]
Hi @hsi1032 @universome , I just uploaded another checkpoint for faceforensics (modelR_epoch_799.pth).

**Comment by universome** [comment]
Hi, thank you! Here is the samples that I got:


https://user-images.githubusercontent.com/3128824/142292512-d62e5173-193a-49b6-bd3b-0e3875ebaf42.mp4

Is it the proper quality or in your case the results are better (note that I use higher FPS when saving the mp4 file)?

**Comment by alanspike** [comment]
Hi, I got something like this

https://user-images.githubusercontent.com/35404050/142292771-d40ca519-3187-4af0-b0ab-077b48c0f686.mp4

**Comment by alanspike** [comment]
@universome There can be repeated patterns if you generate much longer videos as we used 16 frames for training. Looks like the video you shared includes around 125 ish frames.

**Comment by universome** [comment]
@alanspike Ok, thanks! Yes, I understand that some artifacts in my generations are due to longer generation. I believe that I do not have any other questions, so I'm closing the issue, thank you!
