### ISSUE TITLE
Did you cut first seconds of the FaceForensics dataset?

### ISSUE THREAD

**Issue by universome** [snap-research/MoCoGAN-HD#9]
Hi! FaceForensics contains "video starting" artifacts for its first ~0.5 seconds for many its videos (see the gif), which might produce the corresponding training artifacts. Did you remove them?

Here are random samples from FFS, cut to the first 0.5 seconds:

![real_ffs_128_unstable_1s](https://user-images.githubusercontent.com/3128824/136700062-69e71d29-549f-4355-be76-db0339352501.gif)

Also, did you account for them in any way when computing FVD?

**Comment by alanspike** [comment]
Hi, we follow the data processing code from [TGAN v2](https://github.com/pfnet-research/tgan2#faceforensics) for a comparison w/ their methods.

**Comment by universome** [comment]
I see, thank you. I checked the code in TGANv2 and they do not cut the videos in any way
